### ISSUE TITLE
ISSUE | No se visualiza el home correctamente en tablet

### ISSUE THREAD

**Issue by nsdonato** [nsdonato/vamosacodearplanetas#30]
Comportamiento esperado:
https://trello.com/1/cards/637571f0ba1b0f0092830a2b/attachments/637572083c3281012b07a4ea/download/image.png

Resultado:
https://trello.com/1/cards/637571f0ba1b0f0092830a2b/attachments/637571f87b09920111cd8a82/download/image.png

**Comment by ccastillob** [comment]
Este issue se resuelve con el Pull Request #32
