### ISSUE TITLE
ISSUE | No se visualiza correctamente el menu en mobile

### ISSUE THREAD

**Issue by nsdonato** [nsdonato/vamosacodearplanetas#33]
Comportamiento esperado:
![image](https://user-images.githubusercontent.com/7875216/202553326-cf62d80f-cc23-4614-83fa-316f66c7113a.png)

Resultado:
![image](https://user-images.githubusercontent.com/7875216/202552721-2cd63022-9a34-46b4-b3f8-2fac5257471f.png)

**Comment by phreakphreak** [comment]
este issue se cerro en #41
